name = "SymPyCore"
uuid = "458b697b-88f0-4a86-b56b-78b75cfb3531"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "0.2.9"

[deps]
CommonEq = "3709ef60-1bee-4518-9f2f-acd86f176c50"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[weakdeps]
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[extensions]
SymPyCoreTermInterfaceExt = "TermInterface"

[compat]
Aqua = "0.8"
CommonEq = "0.2.1"
CommonSolve = "0.2"
GeneralizedGenerated = "0.3.3"
Latexify = "0.15, 0.16"
LinearAlgebra = "<0.0.1, 1.6"
Markdown = "<0.0.1, 1.6"
RecipesBase = "0.7, 0.8, 1.0, 1.1"
SparseArrays = "1.1"
SpecialFunctions = "0.8, 0.9, 0.10, 1.0, 2"
SymPyPythonCall = "0.3,0.4"
TermInterface = "2"
Test = "<0.0.1, 1.6"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymPyPythonCall = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "TermInterface", "SparseArrays", "SymPyPythonCall", "Test"]
